# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50, null='')),
                ('blog_author', models.CharField(max_length=50, null='')),
                ('blog_date', models.DateField()),
                ('blog_content', models.CharField(max_length=5000, null='')),
                ('blog_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=50, null='')),
                ('program_description', models.CharField(max_length=1000, null='')),
                ('program_department', models.CharField(max_length=50, null='')),
            ],
        ),
    ]
