# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outreach_title', models.CharField(max_length=50, null='')),
                ('outreach_author', models.CharField(max_length=50, null='')),
                ('outreach_date', models.DateField()),
                ('outreach_content', models.CharField(max_length=5000, null='')),
                ('outreach_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='program',
            name='program_description',
            field=models.CharField(max_length=2000, null=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=100, null=''),
        ),
    ]
