# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180128_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=1000, null='')),
                ('news_description', models.CharField(max_length=10000, null='')),
                ('news_author', models.CharField(max_length=1000, null='')),
            ],
        ),
    ]
