# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_newspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='news_image',
            field=models.FileField(null=' ', upload_to=''),
        ),
    ]
