# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_facultymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='faculty_firstsem',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='faculty_secondsem',
            field=models.BooleanField(default=True),
        ),
    ]
