# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20180207_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_title', models.CharField(max_length=1000, null='')),
                ('research_description', models.CharField(max_length=10000, null='')),
                ('research_abstract', models.CharField(max_length=10000, null='')),
                ('research_author', models.CharField(max_length=1000, null='')),
                ('research_resources', models.CharField(max_length=10000, null='')),
            ],
        ),
    ]
