# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_researchtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='news_image',
            field=models.FileField(null='', upload_to=''),
        ),
    ]
