# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_updatepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='news_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
