# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_newspost_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='news_date',
            field=models.DateField(auto_now_add=True, null=''),
        ),
    ]
