# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20180210_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='news_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, null=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspost',
            name='news_author',
            field=models.CharField(help_text='Author of the article', max_length=1000, null=''),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='news_image',
            field=models.FileField(help_text='Headline Image of the article', null='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='news_title',
            field=models.CharField(help_text='Headline', max_length=1000, null=''),
        ),
    ]
