# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20180210_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=1000, null='')),
                ('event_details', models.CharField(max_length=10000, null='')),
                ('event_date', models.DateTimeField(null='')),
                ('event_datecreated', models.DateTimeField(auto_now_add=True, null='')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='UpdatePost',
        ),
    ]
