# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20180224_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='event_time',
            field=models.TimeField(default=django.utils.timezone.now, null=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='event_date',
            field=models.DateField(null=''),
        ),
    ]
