# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20180224_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='news_date',
            field=models.DateField(null=''),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='event_time',
            field=models.TimeField(help_text='Format: HH:MM:SS, 24H. e.g 15:30:00 is 3:30PM', null=''),
        ),
    ]
