# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20180225_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_level',
            field=models.CharField(default='Masters', max_length=1000, null=''),
            preserve_default=False,
        ),
    ]
