# Generated by Django 2.0.2 on 2018-02-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_program_program_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_name', models.CharField(help_text='Full name along with prefix and suffixes.', max_length=1000, null='')),
                ('alumni_description', models.CharField(help_text='Short Bio of the alumni', max_length=5000, null='')),
                ('alumni_contact', models.CharField(help_text='LinkedIn URL, Contact Number', max_length=5000, null='')),
                ('alumni_image', models.FileField(help_text='2x2 or Professional Image of the Alumni', null='', upload_to='')),
            ],
        ),
    ]
