# Generated by Django 2.0.2 on 2018-02-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_title', models.CharField(help_text='Research Title', max_length=5000, null='')),
                ('research_author', models.CharField(help_text='Proponent/s of the research', max_length=1000, null='')),
                ('research_abstract', models.CharField(help_text='A summary or abstract of the research', max_length=10000, null='')),
            ],
        ),
    ]
