# Generated by Django 2.0.2 on 2018-02-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_research'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Research',
        ),
    ]
