# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alumni_alumni_url'),
        ('website', '0009_auto_20180209_0012'),
    ]

    operations = [
    ]
