# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_merge_20180322_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspost',
            old_name='news_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='newspost',
            old_name='news_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='newspost',
            old_name='news_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='newspost',
            old_name='news_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='newspost',
            old_name='news_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='outreachpost',
            old_name='outreach_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='outreachpost',
            old_name='outreach_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='outreachpost',
            old_name='outreach_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='outreachpost',
            old_name='outreach_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='outreachpost',
            old_name='outreach_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='upcomingevent',
            old_name='event_details',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='upcomingevent',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='upcomingevent',
            old_name='event_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='upcomingevent',
            old_name='event_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='news_image',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='news_shortdesc',
        ),
        migrations.AddField(
            model_name='newspost',
            name='image',
            field=models.FileField(help_text='Headline Image of the article', null=True, upload_to=''),
        ),
    ]
