# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20180322_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspost',
            old_name='description',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='outreachpost',
            old_name='content',
            new_name='contents',
        ),
    ]
