# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20180322_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='image',
            field=models.FileField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
