# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20180322_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcomingevent',
            old_name='images',
            new_name='image',
        ),
    ]
