# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20180322_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
