# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20180322_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchtitle',
            name='research_description',
        ),
        migrations.AlterField(
            model_name='researchtitle',
            name='research_abstract',
            field=models.CharField(max_length=50000, null=''),
        ),
    ]
