# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20180326_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchtitle',
            name='research_abstract',
            field=models.TextField(max_length=50000, null=''),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='contents',
            field=models.CharField(max_length=10000, null=''),
        ),
    ]
