# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20180326_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtitle',
            name='research_year',
            field=models.IntegerField(default=' ', null=''),
            preserve_default=False,
        ),
    ]
