# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20180410_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchtitle',
            name='research_year',
        ),
    ]
