# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_researchtitle_research_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchtitle',
            name='research_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
