# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_auto_20180410_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtitle',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.Program'),
        ),
    ]
