# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_auto_20180412_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchtitle',
            name='program',
        ),
    ]
