# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_auto_20180412_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchtitle',
            name='research_year',
        ),
    ]
