# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_remove_researchtitle_research_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtitle',
            name='research_year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
