# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_remove_researchtitle_research_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtitle',
            name='research_program',
            field=models.CharField(default=' ', max_length=1000, null=''),
            preserve_default=False,
        ),
    ]
